version: '3'
networks:
  selenoid:
    external:
      name: selenoid # network should be previously created
services:
  selenoid:
    image: "aerokube/selenoid:1.11.2"
    networks:
      - selenoid
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - ".:/etc/selenoid/" # assumed current dir contains browsers.json
      - "./target:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-container-network", "selenoid"] # flag for created network
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    networks:
      - selenoid
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8083:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  chrome_124.0:
    image: "selenoid/vnc_chrome:124.0"
    container_name: chrome_124.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
  jenkins:
    image: jenkins/jenkins:lts
    networks:
      - selenoid
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock